# To get started, copy this file to `config.yml` and then use one of
# the configurations below to point it at your build server.  You'll
# need to include the line starting with a '-'.  That's how the config
# files knows it's a list.


# List all jobs running on a server
# -
#   url: http://localhost:8080/cc.xml
-
  url: http://ec2-50-17-89-74.compute-1.amazonaws.com:8080/cc.xml


# A server with basic authentication.
# -
#   url: http://localhost:8080/cc.xml
#   username: hudson-user
#   password: hudson-password


# If you have a lot of jobs, and you only want to show the status of some of them,
# try listing them explicitly
# -
#   url: http://localhost:8080/cc.xml
#   username: hudson-user
#   password: hudson-password
#   jobs:
#     - roodi    # the build named "roodi"
#     - /^run/   # all builds starting with "run"
